# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dan Kraus
tagline:          Web Application Developer
description:      "Web Developer, Star Wars fan and collector, R2-D2 Builder, Cool Dude"
url:              www.dskraus.com
paginate:         5
baseurl:          /
author:
  name:           Dan Kraus
  url:            http://www.dskraus.com
  email:          dskraus@gmail.com


# Gravatar
gravatar:         http://www.gravatar.com/avatar/7362bb5fa1a449cbaf3211d5dbeb02aa.png

# Sidebar external links
links:
  -
    title: Twitter
    url: https://twitter.com/DanKrausDev
  -
    title: GitHub
    url: https://github.com/dankraus
  -
    title: LinkedIn
    url: https://www.linkedin.com/pub/dan-kraus/3/3b0/b12
